### ISSUE TITLE
Battery usage is extremely high

### ISSUE THREAD

**Issue by Milo123459** [expressvpn/lightway-core#11]
I'm running iOS 15.1 and the background usage of the app is 29% in the last 24 hours. I'm using the lightway udp protocol and think this might be a bug.

Thank you.

**Comment by expressvpn-pete-m** [comment]
@Milo123459 thanks for raising this as an issue. Lightway Core is the platform independent implementation of Lightway, so this is something that you'd need to report to our support team. You can get more information here: https://www.expressvpn.com/support/  :)

**Comment by Milo123459** [comment]
I spoke to the support team on the 12th of December only to receive nothing back. I thought of filing the issue here as using a different protocol didn't spike in battery usage - hence me thinking to file an issue. I will try again though.

**Comment by expressvpn-pete-m** [comment]
When filing the issue, please ask them to bring it to the attention of Pete M and I'll follow up.
