### ISSUE TITLE
GSoC participation request

### ISSUE THREAD

**Issue by sheharyaar** [expressvpn/lightway-core#13]
Hi guys,

I would like to add TCP functionality to lightway-laser as a project for Google Summer of Code (GSoC), 2022. It would be awesome if expressvpn register as an organisation for GSoC.

Thank You

**Comment by expressvpn-pete-m** [comment]
Hi @sheharyaar,

I think that's a great idea!

I'll try to find out what's involved and see whether or not it's something we can participate in.

Even if not, we would still welcome any contributions you'd like to make :)

**Comment by sheharyaar** [comment]
Yeah, I would love to make contributions. Currently I am a student, so a project for GSoC will surely help a lot to me.

Thanks

**Comment by sheharyaar** [comment]
Hi, is there any update on the process?

**Comment by expressvpn-pete-m** [comment]
Hi @sheharyaar , we were waiting for Google to announce the details for GSoC this year, which only just happened. We are actively looking into this :)

**Comment by sheharyaar** [comment]
Thanks for looking into this. I would love to work under a mentor to contribute for a gsoc project.

**Comment by expressvpn-pete-m** [comment]
@sheharyaar I just wanted to let you know that we have submitted our application to join GSoC :)

I'll let you know when we hear more :)

**Comment by sheharyaar** [comment]
Thank you so much! I am really excited for this. 😊

**Comment by expressvpn-pete-m** [comment]
@sheharyaar Unfortunately we weren't able to secure a spot in the GSoC this year. Google told us that there were many more applicants than available slots and I guess the competition was fierce. We will definitely be trying again next year though with an even better application!

I know you had hoped to work on Lightway as part of the GSoC, but if you still want to work on it, we will still be here to support your efforts :)

**Comment by sheharyaar** [comment]
I feel happy that you submitted the proposal. I have been fascinated with expressvpn since the first time I used it. I would love to contribute to this project. Thank you so much for your efforts :)
