### ISSUE TITLE
Custom Threat Manager blacklist

### ISSUE THREAD

**Issue by ColinStroud** [expressvpn/lightway-core#130]
I'm interested in the Threat Manager and would like the ability to also specify my own set of URLs/URIs in addition to whatever lists are maintained by Express VPN.

## Expected Behavior (new feature)
The ability to define my own set of URLs/URIs which block any outgoing requests made from my computer. Preferably with some support for wildcard or pattern matching of the URIs. Additionally, as any such list could contain sensitive personal or identifying information, I would want to host the file externally (any of local, cloud or 3rd party based storage would suffice). 

## Current Behavior
Currently the only block lists used by the Threat Manager are ones internally stored & maintained by Express VPN (from what I can tell & has been indicated to me by Express VPN). I would like some ability to specifying my own list(s) which can be stored external to Express VPN and also prevent any matching requests from being sent from my computer (or other device(s) if possible).

## Possible Solution
A locally managed list of URI(s) or URI "patterns" which prevent any requests which match from being sent.

## Steps to Reproduce (for bugs)
N/A

## Context
Edit: Forgot to fill in this section, my apologies!
As powerful a tool as general blacklists are at preventing well-known threats, they inherently lack the ability to handle all / specific cases. Also, as is inherent with any general solution (one size fits all), they lack the ability to handle more localized / niche request blocking tailored specifically to an individual user's needs. A locally maintained list (or similar technique) could help bridge these gaps. 

## Your Environment
N/A (not a bug)

## Attachments
In addition to the template sections above, I've attached the chat log from my discussion with the Express VPN support team fyi. If it'd be helpful to tie that support request w/ this feature request (or in case I was remiss in including any details here). See below:

[Support request log.txt](https://github.com/expressvpn/lightway-core/files/12967144/Support.request.log.txt)

## Final Notes
As both a software developer myself and a happy long-time user of Express VPN I understand backlogs, priority, etc. and also understand not all requests can or do get picked up. I know this is a feature I'd personally love to see implemented and imagine that there are others whom may agree. Thanks for all of your hard work & great service EVPN, it's been a pleasure so far!

**Comment by ColinStroud** [comment]
Possibly also worth mentioning is I've already played around with modifying my EVPN client's source code to gain programmatic access so I can toggle certain actions locally. I'll probably look into addition something similar for request blocking (if feasible) in the mean time. I hope this doesn't affect this request at all as any hand-rolled modifications to internal logic / code is inherently fragile and can be prone to bugs (especially my code, or so I worry haha).

**Comment by expressvpn-andre-l** [comment]
@ColinStroud, thanks for reaching out! 
I want to let you know that we've already got something in our backlog for this type of Threat Manager customization.  I can't commit to a date for when we will deliver this, but I will attach this conversation to our existing ticket. That will provide more motivation for us to prioritize this feature higher 😄 . 

As this particular issue is not strictly about the Lightway Core library / protocol. I will close this issue now.
