### ISSUE TITLE
Merge into the linux kernel?

### ISSUE THREAD

**Issue by mystic-githuber** [expressvpn/lightway-core#18]
Do you have plans to merge lightway into the linux kernel? It would be great if you do so!

Any ETA for this?

**Comment by expressvpn-pete-m** [comment]
Hi @mystic-githuber,

Thanks for the question!

At present we have no plans to merge Lightway into the Linux kernel.

By keeping it in user space for now we help ensure that we stay cross platform, avoid duplication of code and have a much simpler code base. There just isn't a compelling reason for us to take on that extra complexity right now.

Having said that, we aren't ruling out considering such a move in the future :)
