### ISSUE TITLE
multi-threading support

### ISSUE THREAD

**Issue by u-sil** [expressvpn/lightway-core#52]
It seems to me that Lightway currently does not use multithreading
I checked both the official version and the beta version on my Raspberry Pi4
Both versions use only one core
use AES, 120mbps is the limit, and ChaCha20 is 170mbps
multithreading is needed for fast speed on mobile devices and SBC

AES on Pi4, no big difference in speed with openvpn
On the Pi4, Wireguard supports multithreading, resulting in very fast speeds of over 500mbps

But ExpressVPN doesn't support Wireguard, so I wish the lightway was as fast as wireguard !

**Comment by expressvpn-pete-m** [comment]
You're quite right that our app uses Lightway in a single thread. This was done for simplicity and security. The downside is that, as you've determined with SBCs (or other systems that depend on using multiple cores to get good general performance) Lightway isn't able to take full advantage of the hardware.

We are actively working in this area at the moment, and although I can't give you a timeline yet, the single threaded issue will be going away 😊

**Comment by u-sil** [comment]
@expressvpn-pete-m thank you for the reply!
I am happy to be able to communicate directly

LiveChat mostly said they would give feedback, but I don't know if it's actually delivered 😅
(I have something to ask the Threat Manager too)

**Comment by expressvpn-pete-m** [comment]
Although I can't help with Threat Manager, I can say that our support team does indeed pass the feedback on to our engineers 😊 

I'm going to close this issue for now, but I'll comment again on it in the future when we can take better advantage of multiple cores 😊
