### ISSUE TITLE
Streaming is not supported yet (tcp mode)?

### ISSUE THREAD

**Issue by Jiw0cha** [expressvpn/lightway-core#53]
Hello.

How to run with ``--protocol tcp``? 

``` sudo ./lw.out --server --protocol tcp --username test --password test --server_ip '0.0.0.0'  --server_port 19655 --cert certs/shared.crt  --key certs/server.key --tun helium-test```

Exit with ```Streaming is not supported yet```

**Comment by expressvpn-pete-m** [comment]
Hi,

Lightway Laser is just an example app and only supports UDP at present. We don't have plans to implement TCP. There was interest in adding TCP support from the community, and a fair bit of work was done here:

https://github.com/expressvpn/lightway-laser/pull/2

However we weren't able to get it working.

If you'd like to implement TCP support (and possibly continue the work already started), I would be very happy to look at a pull request!  😊
