### ISSUE TITLE
fully open-source client for expressvpn lightway

### ISSUE THREAD

**Issue by milahu** [expressvpn/lightway-core#70]
im looking for an actual "open-source" client for expressvpn lightway

i do not want an open-source core with a [closed-source app](https://www.expressvpn.com/vpn-software/vpn-linux)

platform: linux

alternatives:

- https://github.com/pia-foss/manual-connections for wireguard at [privateinternetaccess.com](https://www.privateinternetaccess.com/)
- https://github.com/ProtonVPN/linux-cli for wireguard at [protonvpn.com](https://protonvpn.com/)

see also

- https://fosspost.org/linux-vpn-clients-providers/

**Comment by mrbluecoat** [comment]
Agreed. Even a ToyVPN version of Lightway would be great for learning how to embed the library and hook it up to a simple GUI.

**Comment by expressvpn-pete-m** [comment]
We have a reference implementation called Lightway Laser which is available here:

https://github.com/expressvpn/lightway-laser

We are planning to release more robust open source clients as part of our Rust implementation. Unfortunately I can't give an ETA for this at the moment.

**Comment by mrbluecoat** [comment]
I'm guessing AArch64 isn't supported? Your reference implementation wouldn't build with either Docker or manual ceedling build.
