### ISSUE TITLE
Beta users - feedback and other emails issue

### ISSUE THREAD

**Issue by mbiesiad** [expressvpn/lightway-core#79]
Hi, 

Please feel free to redirect this issue to proper repo if needed or just please let your Team to know.
Not a big deal, but:

## Expected Behavior
User, visitor can easy copy provided email address.

## Current Behavior
Provided emails addresses are as images, so user can not copy this (as email address meaning).

## Possible Solution
Emails there not as a screenshot/image, but allow to copy emails address for users.

## Steps to Reproduce (for bugs)
1. Go to https://www.expressvpn.com/pl/support/knowledge-hub/become-an-expressvpn-beta-user/
2. Scroll down to see many email addresses added as an images

## Context
User have to retype this manualy, can make a typo and it is taking more time than copy.

## Your Environment
NA

Additional information:
Screenshots:
![image](https://user-images.githubusercontent.com/18367606/219871099-f820cb9e-6681-4ca9-8db1-02d3581464dd.png)

![image](https://user-images.githubusercontent.com/18367606/219871112-9a4c9c50-6696-4d9b-98b7-8b6126a36687.png)

Best wishes,

**Comment by expressvpn-pete-m** [comment]
Thanks for the report - I've passed on the feedback to the relevant team :slightly_smiling_face:
